template: |
  # Changelog
  $CHANGES

  See details of [all code changes](https://github.com/MasterControlInc/record-configuration/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) since the previous release

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'github-action'
      - 'infrastructure'
      - 'automation'
      - 'documentation'
  - title: '🏎 Performance'
    label: 'performance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: documentation'
  default: minor