
name: Push to Main

on:
    push:
        branches: [ main ]
jobs:
    publish:
        name: Tag & Publish Main
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.tag_outputs.outputs.version }}
        steps:
            # Check if we should skip
            - name: GitHub | Check PR Labels
              id: skipVersion
              uses: shioyang/check-pr-labels-on-push-action@v1.0.3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                labels: '["skip-version"]'
            - name: GitHub | Label Result
              run: echo "'skip-version' tag found. Skipping Tag & Publish."
              if: steps.skipVersion.outputs.result == 'true'
            # Checkout the code
            # Checkout the code
            - name: Checkout
              if: steps.skipVersion.outputs.result == 'false'
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            # Tag build to get version
            - name: GitHub | Tag build
              if: steps.skipVersion.outputs.result == 'false'
              id: version
              uses: anothrNick/github-tag-action@1.34.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  RELEASE_BRANCHES: main
                  VERBOSE: true
            # Output version tag
            - name: GitHub | Output version
              if: steps.skipVersion.outputs.result == 'false'
              id: tag_outputs
              run: echo "::set-output name=version::${{ steps.version.outputs.new_tag }}"
