
name: Release Main
on:
    workflow_dispatch:
        inputs:
            release-tag:
                description: Version to release. Should be in 'v#.#.#' format
                required: true
jobs:
    release:
        name: Release Main
        runs-on: ubuntu-latest
        steps:
            - name: Starting
              run: echo 'Running release for tag ${{ github.event.inputs.release-tag }}'
            - name: List Releases
              id: list-releases
              uses: octokit/request-action@v2.0.17
              with:
                  route: Get /repos/:repository/releases
                  repository: ${{ github.repository }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Print Releases
              run: echo 'got output ${{ steps.list-releases.outputs.data }}'
            - name: Get Release
              id: get-release
              uses: octokit/request-action@v2.0.17
              with:
                  route: GET /repos/:repository/releases/tags/:tag
                  repository: ${{ github.repository }}
                  tag: ${{ github.event.inputs.release-tag }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Verify Release
              run: echo 'got output ${{ fromJson(steps.get-release.outputs.data) }}'