
name: Release Main
on:
    workflow_dispatch:
        inputs:
            release-tag:
                description: Version to release. Should be in 'v#.#.#' format
                required: true
jobs:
    release:
        name: Release Main
        runs-on: ubuntu-latest
        steps:
            - name: Starting
              run: echo 'Running release for tag ${{ github.event.inputs.release-tag }}'
            # Get all releases
            - name: List Releases
              id: list-releases
              uses: octokit/request-action@v2.0.17
              with:
                  route: Get /repos/:repository/releases
                  repository: ${{ github.repository }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Print Releases
              run: echo 'got output ${{ steps.list-releases.outputs.data }}'
            # Draft release notes
            - name: Drafts Release Notes
              uses: adam-berrio/release-drafter@v0.1.0
              with:
                  prerelease: false
                  name: ${{ github.event.inputs.release-tag }}
                  tag: ${{ github.event.inputs.release-tag }}
                  publish: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
